// src/config/constants.js

// --- TRANSLATION DICTIONARY ---
export const dict = {
  en: {
    "Production Hub": "Production Hub",
    "Secure Operator Access": "Secure Operator Access",
    "Enter Operator PIN": "Enter Operator PIN",
    "Secure Login": "Secure Login",
    "Verifying Credentials...": "Verifying Credentials...",
    "Session Parameters": "Session Parameters",
    "Date": "Date",
    "Shift": "Shift",
    "Morning (AM)": "Morning (AM)",
    "Night (PM)": "Night (PM)",
    "Operator / Supervisor": "Operator / Supervisor",
    "Receiver / Admin Name": "Receiver / Admin Name",
    "QC Inspector": "QC Inspector",
    "Machine No.": "Machine No.",
    "Material Inputs": "Material Inputs",
    "Job Order No.": "Job Order No.",
    "Shift Accumulator (Materials)": "Shift Accumulator (Materials)",
    "Batch No.": "Batch No.",
    "Quantity": "Quantity",
    "+ Add": "+ Add",
    "Total Input Material:": "Total Input Material:",
    "Input Roll Weight (kg)": "Input Roll Weight (kg)",
    "Production Output & Wastage": "Production Output & Wastage",
    "Shift Accumulator (Rolls)": "Shift Accumulator (Rolls)",
    "New Roll Weight (kg)": "New Roll Weight (kg)",
    "+ Add Roll": "+ Add Roll",
    "Accumulated Good Output": "Accumulated Good Output",
    "Actual Good Output": "Actual Good Output",
    "UoM": "UoM",
    "Wastage Generated": "Wastage Generated",
    "Wastage Accumulator": "Wastage Accumulator",
    "Type": "Type",
    "Weight (kg)": "Weight (kg)",
    "Setup Wastage": "Setup Wastage",
    "Process Wastage": "Process Wastage",
    "Machine Downtime": "Machine Downtime",
    "Planned (mins)": "Planned (mins)",
    "Unplanned (mins)": "Unplanned (mins)",
    "Primary Downtime Reason": "Primary Downtime Reason",
    "Finished Goods Packing": "Finished Goods Packing",
    "Packing Size": "Packing Size",
    "Quantity Packed": "Quantity Packed",
    "Standardised Total:": "Standardised Total:",
    "Palletisation Details": "Palletisation Details",
    "Pallet Weight (kg) [Tare/Gross]": "Pallet Weight (kg) [Tare/Gross]",
    "Individual Bag/Carton Accumulator": "Individual Bag/Carton Accumulator",
    "Bag": "Bag",
    "Add Another Bag": "Add Another Bag",
    "Actual Bag Weight submitted:": "Actual Bag Weight submitted:",
    "Dispatch / Shipping": "Dispatch / Shipping",
    "Shipped Quantity (kg)": "Shipped Quantity (kg)",
    "Delivery Order (DO) / Invoice No.": "Delivery Order (DO) / Invoice No.",
    "Raw Material Inwards": "Raw Material Inwards",
    "Material Name / ID": "Material Name / ID",
    "Incoming / Received Amount (kg)": "Incoming / Received Amount (kg)",
    "Supplier Name": "Supplier Name",
    "Purchase Order (PO) No.": "Purchase Order (PO) No.",
    "Storage Location / Zone": "Storage Location / Zone",
    "Quality / Condition Check": "Quality / Condition Check",
    "Quality Control Assessment": "Quality Control Assessment",
    "Job Order No. (Under Inspection)": "Job Order No. (Under Inspection)",
    "Thickness Check (Microns)": "Thickness Check (Microns)",
    "Width Check (mm)": "Width Check (mm)",
    "Seal Integrity Assessment": "Seal Integrity Assessment",
    "Length Check (mm)": "Length Check (mm)",
    "Packing Size (Bag Weight - kg)": "Packing Size (Bag Weight - kg)",
    "Quantity Check (Bags per Pallet)": "Quantity Check (Bags per Pallet)",
    "Total Bags Verified": "Total Bags Verified",
    "Total Pallets Counted": "Total Pallets Counted",
    "Overall QC Remarks / Issues Noted": "Overall QC Remarks / Issues Noted",
    "Machine Inspection": "Machine Inspection",
    "Machine Type": "Machine Type",
    "Filter Status": "Filter Status",
    "Scrap Purged": "Scrap Purged",
    "Sealing Temperature (℃)": "Sealing Temperature (℃)",
    "Blade / Thickness Check": "Blade / Thickness Check",
    "Machine Cleanliness": "Machine Cleanliness",
    "Safety Guards": "Safety Guards",
    "Good": "Good",
    "Needs Change": "Needs Change",
    "Changed": "Changed",
    "Yes": "Yes",
    "No": "No",
    "Status": "Status",
    "Pass": "Pass",
    "Fail": "Fail",
    "N/A": "N/A",
    "Submit Shift Log": "Submit Shift Log",
    "Saving...": "Saving...",
    "Discrepancy Must Be Resolved": "Discrepancy Must Be Resolved",
    "Mass Balance Verified": "Mass Balance Verified",
    "Mass Balance Failed (Discrepancy > 2%)": "Mass Balance Failed (Discrepancy > 2%)",
    "Total Input": "Total Input",
    "Total Output + Wastage": "Total Output + Wastage",
    "Variance": "Variance",
    "Error Margin": "Error Margin",
    "Reason for Discrepancy (Required for Override)": "Reason for Discrepancy (Required for Override)",
    "Dashboard": "Dashboard",
    "Extrusion": "Extrusion",
    "Cutting": "Cutting",
    "Packing": "Packing",
    "Dispatch": "Dispatch",
    "Quality Control": "Quality Control",
    "Incoming Goods": "Incoming Goods",
    "Print": "Print",
    "Exit": "Exit",
    "Optional": "Optional",
    "Evidence Photo (Optional)": "Evidence Photo (Optional)",
    "Tap to take photo or upload": "Tap to take photo or upload",
    "bag": "bag",
    "Mark Job as Complete": "Mark Job as Complete",
    "Flag this order as fully packed and ready for shipping.": "Flag this order as fully packed and ready for shipping.",
    "Ready to Ship Tracker": "Ready to Ship Tracker",
    "Customer": "Customer",
    "Packing Details": "Packing Details",
    "Packed Weight": "Packed Weight",
    "Pending Dispatch": "Pending Dispatch",
    "Container Logistics": "Container Logistics",
    "Container": "Container",
    "Arrival Date": "Arrival Date",
    "Laden Date": "Laden Date",
    "ETD PK Date": "ETD PK Date",
    "Inventory": "Inventory",
    "Warehouse Overview": "Warehouse Overview",
    "Raw Material Stock": "Raw Material Stock",
    "Finished Goods (Pending)": "Finished Goods (Pending)",
    "Total Volume": "Total Volume",
    "Material": "Material",
    "Incoming": "Incoming",
    "Consumed": "Consumed",
    "Current Stock": "Current Stock",
    "Purchase Requisition": "Purchase Requisition",
    "Item Name": "Item Name",
    "Remarks": "Remarks",
    "Resolve": "Resolve",
    "Action": "Action",
    "Job Schedule": "Job Schedule",
    "Job Schedule & Overview": "Job Schedule & Overview",
    "Pending Extrusion": "Pending Extrusion",
    "Pending Cutting": "Pending Cutting",
    "Pending Packing": "Pending Packing",
    "Left to run": "Left to run",
    "Left to cut": "Left to cut",
    "Left to pack": "Left to pack",
    "Run Date": "Run Date",
    "Target": "Target",
    "Unscheduled": "Unscheduled",
    "Job Order Overview": "Job Order Overview",
    "Scheduled Run Date": "Scheduled Run Date",
    "Assigned Machine": "Assigned Machine",
    "Extrusion Pending": "Extrusion Pending",
    "Cutting Pending": "Cutting Pending",
    "Packing Pending": "Packing Pending",
    "Shift Schedule": "Shift Schedule",
    "Shift Target": "Shift Target",
    "Auto-Schedule Jobs": "Auto-Schedule Jobs",
    "Urgency": "Urgency",
    "Ready to Run Tracker": "Ready to Run Tracker",
    "Ready to Cut Tracker": "Ready to Cut Tracker",
    "Ready to Pack Tracker": "Ready to Pack Tracker"
  },
  bn: {
    "Production Hub": "উৎপাদন হাব",
    "Secure Operator Access": "নিরাপদ অপারেটর অ্যাক্সেস",
    "Enter Operator PIN": "অপারেটর পিন লিখুন",
    "Secure Login": "লগইন করুন",
    "Verifying Credentials...": "যাচাই করা হচ্ছে...",
    "Session Parameters": "সেশন প্যারামিটার",
    "Date": "তারিখ",
    "Shift": "শিফট",
    "Morning (AM)": "সকাল (AM)",
    "Night (PM)": "রাত (PM)",
    "Operator / Supervisor": "অপারেটর / সুপারভাইজার",
    "Receiver / Admin Name": "রিসিভার / অ্যাডমিন নাম",
    "QC Inspector": "কিউসি ইন্সপেক্টর",
    "Machine No.": "মেশিন নম্বর",
    "Material Inputs": "কাঁচামাল ইনপুট",
    "Job Order No.": "জব অর্ডার নম্বর (JO)",
    "Shift Accumulator (Materials)": "শিফট অ্যাকুমুলেটর (কাঁচামাল)",
    "Batch No.": "ব্যাচ নম্বর",
    "Quantity": "পরিমাণ",
    "Unit": "একক",
    "+ Add": "+ যোগ করুন",
    "Total Input Material:": "মোট ইনপুট কাঁচামাল:",
    "Input Roll Weight (kg)": "ইনপুট রোল ওজন (কেজি)",
    "Production Output & Wastage": "উৎপাদন আউটপুট এবং বর্জ্য",
    "Shift Accumulator (Rolls)": "শিফট অ্যাকুমুলেটর (রোল)",
    "New Roll Weight (kg)": "নতুন রোলের ওজন (কেজি)",
    "+ Add Roll": "+ রোল যোগ করুন",
    "Accumulated Good Output": "জমে থাকা ভালো আউটপুট",
    "Actual Good Output": "প্রকৃত ভালো আউটপুট",
    "UoM": "একক (UoM)",
    "Wastage Generated": "উৎপাদিত বর্জ্য",
    "Wastage Accumulator": "বর্জ্য অ্যাকুমুলেটর",
    "Type": "ধরন",
    "Weight (kg)": "ওজন (কেজি)",
    "Setup Wastage": "সেটআপ বর্জ্য",
    "Process Wastage": "প্রসেস বর্জ্য",
    "Machine Downtime": "মেশিন ডাউনটাইম",
    "Planned (mins)": "পরিকল্পিত (মিনিট)",
    "Unplanned (mins)": "অপরিকল্পিত (মিনিট)",
    "Primary Downtime Reason": "ডাউনটাইমের প্রধান কারণ",
    "Finished Goods Packing": "প্যাকিং (ফিনিশড গুডস)",
    "Packing Size": "প্যাকিং সাইজ",
    "Quantity Packed": "প্যাক করা পরিমাণ",
    "Standardised Total:": "মোট পরিমাণ:",
    "Palletisation Details": "প্যালেট বিবরণ",
    "Pallet Weight (kg) [Tare/Gross]": "প্যালেটের ওজন (কেজি)",
    "Individual Bag/Carton Accumulator": "ব্যাগ/কার্টন অ্যাকুমুলেটর",
    "Bag": "ব্যাগ",
    "Add Another Bag": "আরও ব্যাগ যোগ করুন",
    "Actual Bag Weight submitted:": "মোট ব্যাগের ওজন:",
    "Dispatch / Shipping": "ডিসপ্যাচ / শিপিং",
    "Shipped Quantity (kg)": "শিপ করা পরিমাণ (কেজি)",
    "Delivery Order (DO) / Invoice No.": "ডেলিভারি অর্ডার (DO) নম্বর",
    "Raw Material Inwards": "কাঁচামাল গ্রহণ",
    "Material Name / ID": "কাঁচামালের নাম / আইডি",
    "Incoming / Received Amount (kg)": "গৃহীত পরিমাণ (কেজি)",
    "Supplier Name": "সরবরাহকারীর নাম",
    "Purchase Order (PO) No.": "পারচেজ অর্ডার (PO) নম্বর",
    "Storage Location / Zone": "স্টোরেজ লোকেশন",
    "Quality / Condition Check": "কোয়ালিটি চেক",
    "Quality Control Assessment": "কোয়ালিটি কন্ট্রোল (QC)",
    "Job Order No. (Under Inspection)": "জব অর্ডার নম্বর (তদন্তাধীন)",
    "Thickness Check (Microns)": "পুরুত্ব চেক (মাইক্রন)",
    "Width Check (mm)": "প্রস্থ চেক (মিমি)",
    "Seal Integrity Assessment": "সিল ইন্টিগ্রিটি চেক",
    "Length Check (mm)": "দৈর্ঘ্য চেক (মিমি)",
    "Packing Size (Bag Weight - kg)": "প্যাকিং সাইজ (ব্যাগের ওজন - কেজি)",
    "Quantity Check (Bags per Pallet)": "পরিমাণ চেক (ব্যাগ প্রতি প্যালেট)",
    "Total Bags Verified": "মোট যাচাইকৃত ব্যাগ",
    "Total Pallets Counted": "মোট গোনা প্যালেট",
    "Overall QC Remarks / Issues Noted": "সার্বিক কিউসি মন্তব্য",
    "Machine Inspection": "মেশিন পরিদর্শন",
    "Machine Type": "মেশিনের ধরন",
    "Filter Status": "ফিল্টার স্ট্যাটাস",
    "Scrap Purged": "স্ক্র্যাপ পার্জ করা হয়েছে",
    "Sealing Temperature (℃)": "সিলিং তাপমাত্রা (℃)",
    "Blade / Thickness Check": "ব্লেড / পুরুত্ব চেক",
    "Machine Cleanliness": "মেশিনের পরিচ্ছন্নতা",
    "Safety Guards": "নিরাপত্তা গার্ড",
    "Good": "ভালো",
    "Needs Change": "পরিবর্তন প্রয়োজন",
    "Changed": "পরিবর্তন করা হয়েছে",
    "Yes": "হ্যাঁ",
    "No": "না",
    "Status": "স্ট্যাটাস",
    "Pass": "পাস",
    "Fail": "ফেইল",
    "N/A": "প্রযোজ্য নয়",
    "Submit Shift Log": "শিফট লগ জমা দিন",
    "Saving...": "সেভ হচ্ছে...",
    "Discrepancy Must Be Resolved": "অসঙ্গতি সমাধান করতে হবে",
    "Mass Balance Verified": "ম্যাস ব্যালেন্স যাচাই করা হয়েছে",
    "Mass Balance Failed (Discrepancy > 2%)": "ম্যাস ব্যালেন্স ফেইল (পার্থক্য > ২%)",
    "Total Input": "মোট ইনপুট",
    "Total Output + Wastage": "মোট আউটপুট + বর্জ্য",
    "Variance": "পার্থক্য",
    "Error Margin": "ভুলের মার্জিন",
    "Reason for Discrepancy (Required for Override)": "অসঙ্গতির কারণ (অপরিহার্য)",
    "Dashboard": "ড্যাশবোর্ড",
    "Extrusion": "এক্সট্রুশন",
    "Cutting": "কাটিং",
    "Packing": "প্যাকিং",
    "Dispatch": "ডিসপ্যাচ",
    "Quality Control": "কিউসি (QC)",
    "Incoming Goods": "ইনকামিং গুডস",
    "Print": "প্রিন্ট",
    "Exit": "প্রস্থান",
    "Optional": "ঐচ্ছিক",
    "Evidence Photo (Optional)": "প্রমাণের ছবি (ঐচ্ছিক)",
    "Tap to take photo or upload": "ছবি তুলতে বা আপলোড করতে ট্যাপ করুন",
    "bag": "ব্যাগ",
    "Mark Job as Complete": "কাজটি সম্পূর্ণ হিসেবে চিহ্নিত করুন",
    "Flag this order as fully packed and ready for shipping.": "এই অর্ডারটি সম্পূর্ণ প্যাক করা এবং শিপিংয়ের জন্য প্রস্তুত হিসেবে ফ্ল্যাগ করুন।",
    "Ready to Ship Tracker": "শিপিংয়ের জন্য প্রস্তুত ট্র্যাকার",
    "Customer": "গ্রাহক",
    "Packing Details": "প্যাকিং বিবরণ",
    "Packed Weight": "প্যাক করা ওজন",
    "Pending Dispatch": "অপেক্ষমাণ ডিসপ্যাচ",
    "Container Logistics": "কনটেইনার লজিস্টিকস",
    "Container": "কনটেইনার",
    "Arrival Date": "আগমনের তারিখ",
    "Laden Date": "লাডেন তারিখ",
    "ETD PK Date": "ইটিডি পিকে তারিখ",
    "Inventory": "ইনভেন্টরি",
    "Warehouse Overview": "গুদাম ওভারভিউ",
    "Raw Material Stock": "কাঁচামাল স্টক",
    "Finished Goods (Pending)": "ফিনিশড গুডস (অপেক্ষমাণ)",
    "Total Volume": "মোট আয়তন",
    "Material": "উপাদান",
    "Incoming": "ইনকামিং",
    "Consumed": "ব্যবহৃত",
    "Current Stock": "বর্তমান স্টক",
    "Purchase Requisition": "ক্রয় রিকুইজিশন",
    "Item Name": "আইটেমের নাম",
    "Remarks": "মন্তব্য",
    "Resolve": "সমাধান করুন",
    "Action": "অ্যাকশন",
    "Job Schedule": "কাজের সময়সূচী",
    "Job Schedule & Overview": "কাজের সময়সূচী এবং ওভারভিউ",
    "Pending Extrusion": "অপেক্ষমাণ এক্সট্রুশন",
    "Pending Cutting": "অপেক্ষমাণ কাটিং",
    "Pending Packing": "অপেক্ষমাণ প্যাকিং",
    "Left to run": "বাকি রান",
    "Left to cut": "বাকি কাট",
    "Left to pack": "বাকি প্যাক",
    "Run Date": "রান তারিখ",
    "Target": "লক্ষ্য",
    "Unscheduled": "অনির্ধারিত",
    "Job Order Overview": "জব অর্ডার ওভারভিউ",
    "Scheduled Run Date": "নির্ধারিত রান তারিখ",
    "Assigned Machine": "বরাদ্দকৃত মেশিন",
    "Extrusion Pending": "এক্সট্রুশন অপেক্ষমাণ",
    "Cutting Pending": "কাটিং অপেক্ষমাণ",
    "Packing Pending": "প্যাকিং অপেক্ষমাণ",
    "Shift Schedule": "শিফট শিডিউল",
    "Shift Target": "শিফট টার্গেট",
    "Auto-Schedule Jobs": "অটো-শিডিউল জবস",
    "Urgency": "জরুরী",
    "Ready to Run Tracker": "রান করার জন্য প্রস্তুত ট্র্যাকার",
    "Ready to Cut Tracker": "কাটার জন্য প্রস্তুত ট্র্যাকার",
    "Ready to Pack Tracker": "প্যাক করার জন্য প্রস্তুত ট্র্যাকার"
  },
  ms: {
    "Production Hub": "Pusat Pengeluaran",
    "Secure Operator Access": "Akses Operator Selamat",
    "Enter Operator PIN": "Masukkan PIN Operator",
    "Secure Login": "Log Masuk Selamat",
    "Verifying Credentials...": "Mengesahkan Kelayakan...",
    "Session Parameters": "Parameter Sesi",
    "Date": "Tarikh",
    "Shift": "Syif",
    "Morning (AM)": "Pagi (AM)",
    "Night (PM)": "Malam (PM)",
    "Operator / Supervisor": "Operator / Penyelia",
    "Receiver / Admin Name": "Penerima / Nama Admin",
    "QC Inspector": "Pemeriksa QC",
    "Machine No.": "No. Mesin",
    "Material Inputs": "Input Bahan",
    "Job Order No.": "No. Pesanan Kerja (JO)",
    "Shift Accumulator (Materials)": "Pengumpul Syif (Bahan)",
    "Batch No.": "No. Kumpulan",
    "Quantity": "Kuantiti",
    "Unit": "Unit",
    "+ Add": "+ Tambah",
    "Total Input Material:": "Jumlah Bahan Input:",
    "Input Roll Weight (kg)": "Berat Gulungan Input (kg)",
    "Production Output & Wastage": "Keluaran Pengeluaran & Sisa",
    "Shift Accumulator (Rolls)": "Pengumpul Syif (Gulungan)",
    "New Roll Weight (kg)": "Berat Gulungan Baru (kg)",
    "+ Add Roll": "+ Tambah Gulungan",
    "Accumulated Good Output": "Terkumpul Keluaran Baik",
    "Actual Good Output": "Keluaran Baik Sebenar",
    "UoM": "Unit",
    "Wastage Generated": "Sisa Terjana",
    "Wastage Accumulator": "Pengumpul Sisa",
    "Type": "Jenis",
    "Weight (kg)": "Berat (kg)",
    "Setup Wastage": "Sisa Persediaan",
    "Process Wastage": "Sisa Proses",
    "Machine Downtime": "Masa Henti Mesin",
    "Planned (mins)": "Dirancang (minit)",
    "Unplanned (mins)": "Tidak Dirancang (minit)",
    "Primary Downtime Reason": "Sebab Utama Masa Henti",
    "Finished Goods Packing": "Pembungkusan Barang Siap",
    "Packing Size": "Saiz Pembungkusan",
    "Quantity Packed": "Kuantiti Dibungkus",
    "Standardised Total:": "Jumlah Standard:",
    "Palletisation Details": "Butiran Pempaletan",
    "Pallet Weight (kg) [Tare/Gross]": "Berat Pallet (kg) [Bersih/Kasar]",
    "Individual Bag/Carton Accumulator": "Pengumpul Beg/Kadbod Individu",
    "Bag": "Beg",
    "Add Another Bag": "Tambah Beg Lain",
    "Actual Bag Weight submitted:": "Berat Beg Sebenar dihantar:",
    "Dispatch / Shipping": "Penghantaran",
    "Shipped Quantity (kg)": "Kuantiti Dihantar (kg)",
    "Delivery Order (DO) / Invoice No.": "No. Pesanan Penghantaran (DO) / Invois",
    "Raw Material Inwards": "Bahan Mentah Masuk",
    "Material Name / ID": "Nama/ID Bahan",
    "Incoming / Received Amount (kg)": "Jumlah Masuk / Diterima (kg)",
    "Supplier Name": "Nama Pembekal",
    "Purchase Order (PO) No.": "No. Pesanan Belian (PO)",
    "Storage Location / Zone": "Lokasi/Zon Simpanan",
    "Quality / Condition Check": "Pemeriksaan Kualiti / Keadaan",
    "Quality Control Assessment": "Penilaian Kawalan Kualiti",
    "Job Order No. (Under Inspection)": "No. Pesanan Kerja (Di Bawah Pemeriksaan)",
    "Thickness Check (Microns)": "Pemeriksaan Ketebalan (Mikron)",
    "Width Check (mm)": "Pemeriksaan Lebar (mm)",
    "Seal Integrity Assessment": "Penilaian Integriti Kedap",
    "Length Check (mm)": "Pemeriksaan Panjang (mm)",
    "Packing Size (Bag Weight - kg)": "Saiz Pembungkusan (Berat Beg - kg)",
    "Quantity Check (Bags per Pallet)": "Pemeriksaan Kuantiti (Beg setiap Pallet)",
    "Total Bags Verified": "Jumlah Beg Disahkan",
    "Total Pallets Counted": "Jumlah Pallet Dikira",
    "Overall QC Remarks / Issues Noted": "Ulasan QC Keseluruhan / Isu Dicatat",
    "Machine Inspection": "Pemeriksaan Mesin",
    "Machine Type": "Jenis Mesin",
    "Filter Status": "Status Penapis",
    "Scrap Purged": "Sisa Dibuang",
    "Sealing Temperature (℃)": "Suhu Pengedap (℃)",
    "Blade / Thickness Check": "Pemeriksaan Bilah / Ketebalan",
    "Machine Cleanliness": "Kebersihan Mesin",
    "Safety Guards": "Pengadang Keselamatan",
    "Good": "Baik",
    "Needs Change": "Perlu Ditukar",
    "Changed": "Telah Ditukar",
    "Yes": "Ya",
    "No": "Tidak",
    "Status": "Status",
    "Pass": "Lulus",
    "Fail": "Gagal",
    "N/A": "N/A",
    "Submit Shift Log": "Hantar Log Syif",
    "Saving...": "Menyimpan...",
    "Discrepancy Must Be Resolved": "Percanggahan Mesti Diselesaikan",
    "Mass Balance Verified": "Imbangan Jisim Disahkan",
    "Mass Balance Failed (Imbangan Jisim Gagal (Percanggahan > 2%))": "Imbangan Jisim Gagal (Percanggahan > 2%)",
    "Total Input": "Jumlah Input",
    "Total Output + Wastage": "Jumlah Keluaran + Sisa",
    "Variance": "Varians",
    "Error Margin": "Margin Ralat",
    "Reason for Discrepancy (Required for Override)": "Sebab Percanggahan (Wajib untuk Override)",
    "Dashboard": "Papan Pemuka",
    "Extrusion": "Penyemperitan (Extrusion)",
    "Cutting": "Pemotongan",
    "Packing": "Pembungkusan",
    "Dispatch": "Penghantaran",
    "Quality Control": "Kawalan Kualiti (QC)",
    "Incoming Goods": "Barang Masuk",
    "Print": "Cetak",
    "Exit": "Keluar",
    "Optional": "Pilihan",
    "Evidence Photo (Optional)": "Gambar Bukti (Pilihan)",
    "Tap to take photo or upload": "Ketik untuk mengambil gambar atau muat naik",
    "bag": "beg",
    "Mark Job as Complete": "Tandakan Kerja sebagai Selesai",
    "Flag this order as fully packed and ready for shipping.": "Tandakan pesanan ini sebagai siap dibungkus dan sedia untuk penghantaran.",
    "Ready to Ship Tracker": "Penjejak Sedia untuk Dihantar",
    "Customer": "Pelanggan",
    "Packing Details": "Butiran Pembungkusan",
    "Packed Weight": "Berat Dibungkus",
    "Pending Dispatch": "Penghantaran Tertunda",
    "Container Logistics": "Logistik Kontena",
    "Container": "Kontena",
    "Arrival Date": "Tarikh Ketibaan",
    "Laden Date": "Tarikh Muatan (Laden)",
    "ETD PK Date": "Tarikh ETD PK",
    "Inventory": "Inventori",
    "Warehouse Overview": "Gambaran Keseluruhan Gudang",
    "Raw Material Stock": "Stok Bahan Mentah",
    "Finished Goods (Pending)": "Barang Siap (Tertunda)",
    "Total Volume": "Jumlah Isipadu",
    "Material": "Bahan",
    "Incoming": "Masuk",
    "Consumed": "Digunakan",
    "Current Stock": "Stok Semasa",
    "Purchase Requisition": "Permintaan Pembelian",
    "Item Name": "Nama Item",
    "Remarks": "Catatan",
    "Resolve": "Selesaikan",
    "Action": "Tindakan",
    "Job Schedule": "Jadual Kerja",
    "Job Schedule & Overview": "Jadual Kerja & Gambaran Keseluruhan",
    "Pending Extrusion": "Penyemperitan Tertunda",
    "Pending Cutting": "Pemotongan Tertunda",
    "Pending Packing": "Pembungkusan Tertunda",
    "Left to run": "Baki untuk dijalankan",
    "Left to cut": "Baki untuk dipotong",
    "Left to pack": "Baki untuk dibungkus",
    "Run Date": "Tarikh Larian",
    "Target": "Sasaran",
    "Unscheduled": "Tidak Dijadualkan",
    "Job Order Overview": "Gambaran Keseluruhan Pesanan Kerja",
    "Scheduled Run Date": "Tarikh Larian Dijadualkan",
    "Assigned Machine": "Mesin Ditugaskan",
    "Extrusion Pending": "Penyemperitan Tertunda",
    "Cutting Pending": "Pemotongan Tertunda",
    "Packing Pending": "Pembungkusan Tertunda",
    "Shift Schedule": "Jadual Syif",
    "Shift Target": "Sasaran Syif",
    "Auto-Schedule Jobs": "Jadual Auto",
    "Urgency": "Kecemasan",
    "Ready to Run Tracker": "Penjejak Sedia untuk Dijalankan",
    "Ready to Cut Tracker": "Penjejak Sedia untuk Dipotong",
    "Ready to Pack Tracker": "Penjejak Sedia untuk Dibungkus"
  }
};

// --- CONFIGURATION ENGINE ---
export const SCHEDULING_CONFIG = {
  capacities: {
    extrusion: { default: 3000, 'B6': 3000 },
    cutting: { defaultKg: 3000, defaultPcs: 4000, 'C5_pcs': 4000 },
    packing: { kg: 6750, pcs: 45000 } // Approx 450 bags/shift
  },
  concurrency: {
    // Pipeline Variables for Concurrent Manufacturing (Just-In-Time)
    rollWeightKg: 180,               // Standard weight of a roll before it is moved to cutting
    transitTimeMins: 30,             // Time needed to weigh, QA, and move the roll to the next machine
    packBatchPcs: 150,               // Target pcs needed to trigger the packing team to start
    packBatchKg: 50                  // Target kg needed to trigger the packing team to start (if order is in kg)
  },
  extrusionRoutingRules: [
    // The algorithm evaluates these top-to-bottom. It will use the first rule that matches.
    { material: 'HDPE', minWidth: 700, maxWidth: Infinity, machines: ['B8'] },
    { material: 'HDPE', minWidth: 0, maxWidth: 699.99, machines: ['B1', 'B8'] },
    { material: 'LDPE', minWidth: 1800.01, maxWidth: Infinity, machines: ['B6'] },
    { material: 'LDPE', minWidth: 1200, maxWidth: 1800, machines: ['B4', 'B5'] },
    { material: 'LDPE', minWidth: 700, maxWidth: 1199.99, machines: ['B9', 'B4', 'B5'] },
    { material: 'LDPE', minWidth: 0, maxWidth: 699.99, machines: ['B2', 'B9'] }
  ],
  defaultExtrusionMachines: ['B1','B2','B3','B4','B5','B6','B7','B8','B9']
};

// --- GLOBAL VARIABLES & DEFAULTS ---
export const STORAGE_KEY = 'dpr_draft_session';

// YOUR GOOGLE SCRIPT URL HERE
export const GOOGLE_SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbx6ujaHy7rR2sv0bp1GAKq341jePcwR9GQqUQBJL9YBXh-NPCB-QmLwtRoQsWmt48-nqg/exec';

export const defaultStats = { output: 0, prevOutput: 0, consumption: 0, prevConsumption: 0, wastage: 0, prevWastage: 0, units: 0, pallets: 0 };
export const defaultAnalytics = { daily: defaultStats, weekly: defaultStats, monthly: defaultStats, yearly: defaultStats };
